imports:
    - { resource: "processors.yaml" }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Synolia\SyliusAkeneoPlugin\:
        resource: '../../*'
        exclude: '../../{Controller,DependencyInjection,Fixture,Model,Migrations,Payload,Processor,SynoliaSyliusAkeneoPlugin.php}'

    Synolia\SyliusAkeneoPlugin\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Synolia\SyliusAkeneoPlugin\Fixture\:
        resource: '../../Fixture'
        tags: ['sylius_fixtures.fixture']

    Synolia\SyliusAkeneoPlugin\Menu\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

    Synolia\SyliusAkeneoPlugin\Repository\ProductFiltersRulesRepository:
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@sylius.product_filters_rules_class_metadata'

    sylius.product_filters_rules_class_metadata:
        class: 'Doctrine\Common\Persistence\Mapping\ClassMetadata'
        factory: ['@doctrine.orm.entity_manager', getClassMetadata]
        arguments:
            - '@Synolia\SyliusAkeneoPlugin\Entity\ProductFiltersRules'

    Synolia\SyliusAkeneoPlugin\Repository\ProductConfigurationRepository:
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@sylius.product_configuration_class_metadata'

    sylius.product_configuration_class_metadata:
        class: 'Doctrine\Common\Persistence\Mapping\ClassMetadata'
        factory: ['@doctrine.orm.entity_manager', getClassMetadata]
        arguments:
            - '@Synolia\SyliusAkeneoPlugin\Entity\ProductConfiguration'

    Synolia\SyliusAkeneoPlugin\Repository\CategoryConfigurationRepository:
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@akeneo.category_configuration_class_metadata'

    akeneo.category_configuration_class_metadata:
        class: 'Doctrine\Common\Persistence\Mapping\ClassMetadata'
        factory: ['@doctrine.orm.entity_manager', getClassMetadata]
        arguments:
            - '@Synolia\SyliusAkeneoPlugin\Entity\CategoryConfiguration'

    Synolia\SyliusAkeneoPlugin\Repository\ProductGroupRepository:
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@akeneo.product_group'

    akeneo.product_group:
        class: 'Doctrine\Common\Persistence\Mapping\ClassMetadata'
        factory: ['@doctrine.orm.entity_manager', getClassMetadata]
        arguments:
            - '@Synolia\SyliusAkeneoPlugin\Entity\ProductGroup'

    akeneo.setting_class_metadata:
        class: 'Doctrine\Common\Persistence\Mapping\ClassMetadata'
        factory: ['@doctrine.orm.entity_manager', getClassMetadata]
        arguments:
            - '@Synolia\SyliusAkeneoPlugin\Entity\Setting'

    Akeneo\PimEnterprise\ApiClient\AkeneoPimEnterpriseClientInterface:
        factory: ['@Synolia\SyliusAkeneoPlugin\Client\ClientFactory', 'createFromApiCredentials']
        lazy: true

    Synolia\SyliusAkeneoPlugin\Form\Type\AttributeTypeChoiceType:
        arguments:
            - '%sylius.attribute.attribute_types%'

    sylius.attribute_type.reference_entity:
        class: Synolia\SyliusAkeneoPlugin\Component\Attribute\AttributeType\ReferenceEntityAttributeType
        tags:
            - { name: 'sylius.attribute.type', attribute_type: 'reference_entity', label: 'Text', form_type: 'Synolia\SyliusAkeneoPlugin\Form\Type\AttributeType\ReferenceEntityAttributeType', configuration_form_type: 'Synolia\SyliusAkeneoPlugin\Component\Attribute\AttributeType\Configuration\ReferenceEntityAttributeType' }

    serializer.name_converter.camel_case_to_snake_case:
        class: Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter

    Synolia\SyliusAkeneoPlugin\Provider\AkeneoAttributeProcessorProviderInterface:
        class: Synolia\SyliusAkeneoPlugin\Provider\AkeneoAttributeProcessorProvider
        arguments:
            - !tagged_iterator { tag: !php/const Synolia\SyliusAkeneoPlugin\Processor\ProductAttribute\AkeneoAttributeProcessorInterface::TAG_ID, default_priority_method: getDefaultPriority }

    Synolia\SyliusAkeneoPlugin\Provider\ProductRefEntityAttributeValueValueBuilderProviderInterface:
        class: Synolia\SyliusAkeneoPlugin\Provider\ProductRefEntityAttributeValueValueBuilderProvider
        arguments:
            - !tagged_iterator { tag: !php/const Synolia\SyliusAkeneoPlugin\Processor\ProductAttributeValue\ReferenceEntity\ReferenceEntityAttributeValueProcessorInterface::TAG_ID, default_priority_method: getDefaultPriority }

    Synolia\SyliusAkeneoPlugin\Processor\ProductGroup\FamilyVariationAxeProcessor: ~